### ISSUE TITLE
Upgrade Webpack to latest version

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/mullet#108]
Upgrade Webpack to latest version (fix Greenkeeper branch greenkeeper/webpack-4.22.0)

**Comment by Jayadev6191** [comment]
Can I take this ?

**Comment by Jayadev6191** [comment]
#109 Updated webpack to the latest version 🎉😀

**Comment by Jayadev6191** [comment]
@lynnaloo Can you review #109 and let me know if I'm missing anything ? Thanks! :)
