### ISSUE TITLE
Yo generator

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [lynnaloo/mullet#11]
Hi! This mullet stack is awesome! I enjoyed so much!

But I have one question, are you intend to build a yeoman generator to create a scaffold using this stack?

thanks!

**Comment by TheAlphaNerd** [comment]
there is a yeoman generator generator that you can use to simplify the process.

Whether or not it would be overkill is another question... having written one before I found that it was quite a large tech stack to essentially do a bit of regex.  That is assuming you are not compartmentalizing some of the workflow itself... although I would imagine that would be the job of a react or hapi generator.

**Comment by lynnaloo** [comment]
@weyj4 let's :shipit:

**Comment by weyj4** [comment]
Sounds good! Will get on this.
