### ISSUE TITLE
Errors when running `grunt watch`

### ISSUE THREAD

**Issue by mattapperson** [lynnaloo/mullet#15]
Running "jshint:all" (jshint) task

   src/react_components/main.jsx
     10 |    Facebook(null),
             ^ Missing 'new' prefix when invoking a constructor.

>> 1 error in 2 files
Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

**Comment by lynnaloo** [comment]
Good catch. Thanks, I'll look at this and push a fix.
