### ISSUE TITLE
Move from Grunt to ?

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/mullet#16]
Can better deal with source maps/debugging with Gulp.

**Comment by TheAlphaNerd** [comment]
I already got started on an ```npm only``` version that would also provide source maps / debugging 

It is the options -dv to the browserify / watchify cli

You can find the start here --> https://github.com/thealphanerd/mullet/tree/remove-grunt

It is super rough and not stable though

**Comment by lynnaloo** [comment]
Great! Thanks for the help.
