### ISSUE TITLE
Add Hapi/React support for Node v4.2

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/mullet#38]
* Update React to 0.14.*
* Update Hapi to 11.1.*

**Comment by fa7ad** [comment]
bump! any updates on this?

**Comment by lynnaloo** [comment]
This is on my list of things to update in the next month (if someone else doesn't submit a PR before then)

**Comment by fa7ad** [comment]
thanks, great project btw :D

**Comment by lynnaloo** [comment]
Closing this for now because I'm doing some bigger refactoring and then releasing a new version.
