### ISSUE TITLE
Add Jest snapshots 

### ISSUE THREAD

**Issue by troy0820** [lynnaloo/mullet#50]
**Are you asking if this repository is abandoned?**

No, because I read the README.md.

**Have you searched the existing issues to see if your problem has already been addressed?**

Yes.

**Is this a bug or a feature request?**

It's more of a feature/request 

**Are you using Mullet in production?**

No, because that would be ridiculous.

I saw the power of Jest snapshots at ReactConf and it would be awesome to add that to this project.

**Comment by lynnaloo** [comment]
I added these, but then decided it was too much for a simple boilerplate.
