### ISSUE TITLE
Styled-components? 

### ISSUE THREAD

**Issue by troy0820** [lynnaloo/mullet#51]
**Are you asking if this repository is abandoned?**

No, because I read the README.md.

**Have you searched the existing issues to see if your problem has already been addressed?**

Yes.

**Is this a bug or a feature request?**

Feature maybe?

**Are you using Mullet in production?**

No, because that would be ridiculous.

I'm not sure how far you want to bring this project because I know it's a starter but styled-components look really awesome 👍 😄 🐱

**Comment by lynnaloo** [comment]
I think it's too much, but I'm going to consider it since Bootstrap is eventually going away.

**Comment by lynnaloo** [comment]
You should craft a PR and we can decide if it's a benefit or complexity add.

**Comment by lynnaloo** [comment]
I just realized that one of the people behind styled components also does `react-boilerplate` so I'm going to pass on this for now since it's already in that other starter kit. Keep the ideas coming @troy0820 :1st_place_medal:
