### ISSUE TITLE
Upgrade to latest version of React (including necessary refactoring)

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/mullet#53]
- Fix deprecation warnings in React 15 and refactoring necessary to prepare for 16.

**Comment by vudduu** [comment]
Hi, I upgraded to latest version of React.
There were some needed libraries to complete the task.

To support React:
"prop-types": "^15.6.2",

To support tests environment.
"enzyme": "^3.7.0",
"enzyme-adapter-react-16": "^1.6.0",
"jest-cli": "^21.0.0",
"react-addons-test-utils": "^15.6.2",
"react-test-renderer": "^16.5.2"

> It needs a `npm run webpack` to generate new `app.built.js`.
